### ISSUE TITLE
cannot read split property of null on docker start

### ISSUE THREAD

**Issue by aoighost** [zodern/meteor-docker#2]
It's not starting with this command:
$containerName = "meteor-docker-levelup-dev"
$containerPort1 = "17687"
$imageFileName = "meteor-nodejs-i"
$dockerFile = "Dockerfile"

#docker run --name my-meteor-app meteor-app

docker run -it -d --name $containerName --publish=17687:17687 --volume=$HOME/levelup/data:/home/meteor/src $imageFileName

The log output Is this:
PS D:\Dev\meteor-docker> docker logs meteor-docker-levelup-dev
=> Setting node version
/home/app/scripts/node-version.js:59
  var majorVersion = nodeVersion.split('.')[0];
                                 ^

TypeError: Cannot read property 'split' of null
    at Object.<anonymous> (/home/app/scripts/node-version.js:59:34)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Function.Module.runMain (module.js:653:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
PS D:\Dev\meteor-docker> docker logs meteor-docker-levelup-dev more
"docker logs" requires exactly 1 argument.
See 'docker logs --help'.

**Comment by zodern** [comment]
The volume isn't putting the app's bundle where the docker image looks. 
`$HOME/levelup/data:/home/meteor/src` should be `$HOME/levelup/data:/bundle` if you are using the compressed bundle from `meteor build`.

**Comment by zodern** [comment]
I updated the documentation to make this more clear.
