### ISSUE TITLE
Install apt packages (using MUP) as non-root user

### ISSUE THREAD

**Issue by jankapunkt** [zodern/meteor-docker#20]
I am using this with mup 1.5.3 and have some apt packages to install:

```js
{
  ...
    docker: {
      // change to 'abernix/meteord:base' if your app is using Meteor 1.4 - 1.5
      image: 'zodern/meteor',
      buildInstructions: [
        'RUN apt-get update && apt-get install -y imagemagick graphicsmagick'
      ],
  ... 
}
```

That will obviusly fail since it won't run as root user. However I would like to avoid using the `zodern/meteor:root` since it also runs the app via root user, right?

What would be the best way to solve this?

Edit: I currently install these packages manually but I don't see it as a "solution" but rather as a workaround.

**Comment by zodern** [comment]
You can add instructions to change the user. For example:

```
buildInstructions: [
  'USER root',
  'RUN apt-get update && apt-get install -y imagemagick graphicsmagick',
  'USER app'
]
```
