### ISSUE TITLE
node 14 for meteor 2.5.1

### ISSUE THREAD

**Issue by guillim** [zodern/meteor-docker#25]
Hello,
I think it will be time for an update of the docker image. I took the opportunity to test this Dockerfile

```bash
FROM abernix/meteord:node-12-base
ENV NODE_VERSION=14.18.2
RUN apt install -y curl
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
ENV NVM_DIR=/root/.nvm
RUN . "$NVM_DIR/nvm.sh" && nvm install ${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm use v${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm alias default v${NODE_VERSION}
ENV PATH="/root/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"
RUN node --version
RUN npm --version
```

It works well on my new image => `docker pull guillim/meteord:node14.18.2`

**Comment by zodern** [comment]
This image automatically uses the correct Node version. It has several already installed, and if none of them are compatible with the current version of Meteor it has `nvm` download and use the correct version.
