### ISSUE TITLE
setup_nvm.sh incorrectly checking for file instead of folder

### ISSUE THREAD

**Issue by SeraVault** [zodern/meteor-docker#36]
When deploying the docker image zodern/meteor-docker, the meteor app won't start because it always tries to copy node to a folder that already exists.

I believe

if [ -f $NODE_INSTALL_PATH ]; then

should be

if [ -d $NODE_INSTALL_PATH ]; then

**Comment by sitiarel** [comment]
@SeraVault Did you solve the problem?

**Comment by zodern** [comment]
This is fixed in version 0.7.2

**Comment by SeraVault** [comment]
Thanks!
