### ISSUE TITLE
Issue with Node Version

### ISSUE THREAD

**Issue by marcoschwartz** [zodern/meteor-docker#7]
Hello,

As I need phantomJS installed for my Meteor app, I just switched one of my projects to the "zodern/meteor:root" image. 

However, I checked inside the docker image (with docker exec -it ... bash) and I saw that the Node.js version is 4.8.4, which is not the correct version for my Meteor app (version 1.7.0.1). I also tried by putting this image: "zodern/meteor:0.5.0-root", but same result. 

Is there something I am doing wrong? Thanks!

**Comment by aliogaili** [comment]
I'm also having issue with Meteor 1.7 and the zodern/meteor:root I think it was complaining about N-API support and my guest is that it's due to the Node.js version.

**Comment by s7dhansh** [comment]
@zodern there is no meteor up 1.5. The latest is 1.4.5.

**Comment by jamesgibson14** [comment]
I have seen this bug in Meteor 1.7 and 1.8 as well, Sometimes I have been deploying to Ubuntu 18.04 when the error happens, and if I rebuild my server as Ubuntu 16.04 the mup deploy will work. I have deployed successfully many time so Ubuntu 18.04. so I don't know what is causing this.
Any update?

**Comment by zodern** [comment]
I think as of Meteor Up 1.5 and zodern/meteor 0.6, all issues with the node version have been fixed.
