### ISSUE TITLE
[Question] set METEOR_SETTINGS Variable at build time

### ISSUE THREAD

**Issue by tea7day** [zodern/meteor-docker#9]
Can I specify METEOR_SETTINGS environment variable as build-time variable?

e.g. `$ docker build --build-arg METEOR_SETTINGS=jsonstring -t metoer_app .`

**Comment by klokie** [comment]
I have the same question. We've been struggling for days with this build process and haven't gotten it to work.
Basically we're building the Meteor app with 
```
METEOR_SETTINGS="$(cat $METEOR_SETTINGS_FILE)"
export METEOR_SETTINGS
```
The app starts fine when run via CLI, either using `ROOT_URL=$ROOT_URL MONGO_URL="$MONGO_URL" node main.js` or via `forever`, and we've tried both methods described in the readme ("Compressed bundle" and "Built app"). Yet, the settings don't seem to make their way into the app - we get errors on startup. Can you please lend some insight into what's wrong?

**Comment by zodern** [comment]
If you want to set the env vars during build time, you can create a new Dockerfile, and set the `FROM` to be `zodern:meteor`:

```
FROM zodern/meteor
ENV METEOR_SETTINGS=<Meteor settings here>
COPY --chown=app:app ./path/to/bundle /built_app
RUN cd /built_app/programs/server && npm install
```
You could also use a [build arg](https://docs.docker.com/engine/reference/builder/#arg) to set the value for the METEOR_SETTINGS env var.
